### ISSUE TITLE
Erro ao autenticar via Facebook pelo smartphone

### ISSUE THREAD

**Issue by ericksonnascimento** [lamattina/Choice#2]
Ao clicar no botão para se autenticar usando uma conta do Facebook, o sistema apresenta a seguinte mensagem de erro:
"Error: There are no login transports avaliable for The requested method.
O Login falhou"

Navegador: Chrome for iOS
SO: iOS 9.3.3

**Comment by lamattina** [comment]
Erickson,

Inclui autenticação via Github, também.
Sobre o seu problema, fiz dois testes:
1) Safari, que funcionou corretamente;
2) Chrome, onde precisei desativar o bloqueador de popup e mudar a exibição do navegador para modo Desktop.
Por favor, faça um novo teste.

Obrigado!

**Comment by ericksonnascimento** [comment]
Eduardo,

1) Safari ok.
2) No Chrome, apenas alterando para modo Desktop, tanto o modo de autenticação via Facebook como via Github funcionaram perfeitamente.

**Comment by lamattina** [comment]
Opa, legal!
Vou incluir mais uma opção, mas a ideia é consumir a API do André LAB1024 / AB Treinamentos.


Obrigado pelo retorno.
